const DEVELOPMENT_FIXTURES = Object.freeze({
  personas: [
    {
      key: "priya-sharma",
      slug: "priya-sharma",
      displayName: "Priya Sharma",
      headline: "Software Engineer · Coding Educator",
      biography: "A practical software educator focused on helping beginners understand modern web development through clear explanations, small projects, and strong fundamentals.",
      creatorTypes: ["educator", "writer"],
      specialties: ["JavaScript", "React", "Node.js", "Web Development"],
      topics: ["Coding", "Software Development", "JavaScript", "React"],
      languages: ["English", "Hindi"],
      intendedFormats: ["course", "video", "article", "resource"],
      isFeatured: true,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "videos", "articles", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-react-fundamentals" },
    },
    {
      key: "arun-mehta",
      slug: "arun-mehta",
      displayName: "Arun Mehta",
      headline: "SAP Consultant · Enterprise Systems Educator",
      biography: "An enterprise-systems educator who explains SAP concepts through practical business scenarios, process maps, and structured learning paths.",
      creatorTypes: ["educator", "specialist"],
      specialties: ["SAP", "SAP FICO", "S/4HANA", "Enterprise Systems"],
      topics: ["SAP", "ERP", "Finance Systems", "Professional Skills"],
      languages: ["English", "Hindi"],
      intendedFormats: ["course", "video", "article", "resource"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "videos", "articles", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-sap-fico-foundations" },
    },
    {
      key: "ravi-menon",
      slug: "ravi-menon",
      displayName: "Ravi Menon",
      headline: "Government Exam Educator · Quantitative Aptitude",
      biography: "An exam-preparation educator focused on concept clarity, timed practice, problem-solving strategies, and structured revision.",
      creatorTypes: ["educator"],
      specialties: ["Quantitative Aptitude", "Reasoning", "SSC Preparation", "Banking Exams"],
      topics: ["Government Exams", "Aptitude", "Reasoning", "Exam Preparation"],
      languages: ["English", "Malayalam", "Hindi"],
      intendedFormats: ["course", "video", "resource"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-quantitative-aptitude" },
    },
    {
      key: "maya-thomas",
      slug: "maya-thomas",
      displayName: "Maya Thomas",
      headline: "Writer · Storyteller",
      biography: "A writer exploring ordinary turning points, travel, relationships, belonging, and the lessons people carry from one chapter of life into another.",
      creatorTypes: ["writer", "storyteller"],
      specialties: ["Personal Essays", "Travel Writing", "Life Transitions", "Reflection"],
      topics: ["Life", "Travel", "Relationships", "Personal Growth"],
      languages: ["English", "Malayalam"],
      intendedFormats: ["story", "article"],
      isFeatured: true,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["stories", "articles", "about"],
      suggestedFeatured: { contentType: "story", key: "story-city-almost-left-behind" },
    },
    {
      key: "neha-kapoor",
      slug: "neha-kapoor",
      displayName: "Neha Kapoor",
      headline: "Career Educator · Podcast Host",
      biography: "A career educator helping early professionals make clearer career decisions, communicate better, and navigate interviews and workplace transitions.",
      creatorTypes: ["educator", "podcaster"],
      specialties: ["Career Planning", "Interviews", "Communication", "Workplace Growth"],
      topics: ["Career", "Communication", "Personal Development"],
      languages: ["English", "Hindi"],
      intendedFormats: ["podcast", "video", "article", "course"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["podcasts", "courses", "articles", "about"],
      suggestedFeatured: { contentType: "article", key: "article-career-without-perfect-plan" },
    },
    {
      key: "karan-iyer",
      slug: "karan-iyer",
      displayName: "Karan Iyer",
      headline: "Business Educator · Startup Mentor",
      biography: "A business educator focused on practical decision-making, customer understanding, sustainable growth, and turning ideas into testable products.",
      creatorTypes: ["educator", "specialist"],
      specialties: ["Business Fundamentals", "Entrepreneurship", "Product Thinking", "Small Business"],
      topics: ["Business", "Entrepreneurship", "Product", "Career"],
      languages: ["English", "Tamil"],
      intendedFormats: ["course", "article", "video", "resource"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "articles", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-business-fundamentals" },
    },
    {
      key: "ananya-rao",
      slug: "ananya-rao",
      displayName: "Ananya Rao",
      headline: "Personal Finance Educator",
      biography: "A personal-finance educator focused on budgeting, saving, financial organization, and practical money habits.",
      creatorTypes: ["educator", "writer"],
      specialties: ["Budgeting", "Saving", "Financial Planning", "Money Habits"],
      topics: ["Personal Finance", "Money", "Planning"],
      languages: ["English", "Kannada"],
      intendedFormats: ["course", "article", "video", "resource"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "articles", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-personal-budget" },
    },
    {
      key: "aisha-khan",
      slug: "aisha-khan",
      displayName: "Aisha Khan",
      headline: "Product Designer · Design Educator",
      biography: "A design educator teaching practical interface thinking, UX fundamentals, visual hierarchy, and reusable product-design systems.",
      creatorTypes: ["educator", "specialist"],
      specialties: ["UI Design", "UX", "Design Systems", "Product Design"],
      topics: ["Design", "UX", "UI", "Product"],
      languages: ["English", "Hindi"],
      intendedFormats: ["course", "video", "article", "resource"],
      isFeatured: true,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "articles", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-ui-foundations" },
    },
    {
      key: "daniel-joseph",
      slug: "daniel-joseph",
      displayName: "Daniel Joseph",
      headline: "Communication Coach · English Educator",
      biography: "A communication educator helping learners speak more clearly, structure ideas confidently, and improve everyday professional English.",
      creatorTypes: ["educator"],
      specialties: ["Spoken English", "Communication", "Presentation Skills", "Workplace English"],
      topics: ["Languages", "Communication", "Career"],
      languages: ["English", "Malayalam"],
      intendedFormats: ["course", "video", "podcast", "resource"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "videos", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-professional-english" },
    },
    {
      key: "meera-nair",
      slug: "meera-nair",
      displayName: "Meera Nair",
      headline: "Personal Growth Educator · Podcast Host",
      biography: "A personal-growth creator exploring consistency, setbacks, reflection, motivation, and practical ways to keep moving through difficult seasons.",
      creatorTypes: ["podcaster", "writer", "educator"],
      specialties: ["Motivation", "Habits", "Reflection", "Personal Growth"],
      topics: ["Motivation", "Personal Growth", "Life"],
      languages: ["English", "Malayalam"],
      intendedFormats: ["podcast", "article", "video"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["podcasts", "articles", "about"],
      suggestedFeatured: { contentType: "article", key: "article-starting-again" },
    },
    {
      key: "vikram-sen",
      slug: "vikram-sen",
      displayName: "Vikram Sen",
      headline: "Data Analyst · Analytics Educator",
      biography: "A data analytics educator specializing in structured SQL, data modeling, and practical analytical workflows for business insights.",
      creatorTypes: ["educator", "specialist"],
      specialties: ["Excel", "SQL", "Data Analysis", "Power BI"],
      topics: ["Data", "Analytics", "Technology", "Career"],
      languages: ["English", "Hindi"],
      intendedFormats: ["course", "video", "resource", "article"],
      isFeatured: false,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "articles", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-sql-data-analysis" },
    },
    {
      key: "leena-george",
      slug: "leena-george",
      displayName: "Leena George",
      headline: "Educator · Writer · Podcast Host",
      biography: "A multi-disciplinary creator working across structured courses, narrative essays, and podcast conversations on learning, career clarity, and craft.",
      creatorTypes: ["educator", "writer", "podcaster"],
      specialties: ["Learning", "Career", "Personal Growth", "Communication"],
      topics: ["Education", "Career", "Personal Growth"],
      languages: ["English", "Malayalam", "Hindi"],
      intendedFormats: ["course", "article", "story", "podcast", "video", "resource"],
      isFeatured: true,
      applicationStatus: "active",
      profileStatus: "active",
      isPublic: true,
      moduleOrder: ["courses", "articles", "stories", "podcasts", "resources", "about"],
      suggestedFeatured: { contentType: "course", key: "course-lifelong-learning" },
    },
    // Non-public workflow fixtures for test contracts
    {
      key: "workflow-approved-creator",
      slug: "workflow-aditi-verma",
      displayName: "Aditi Verma",
      headline: "Instructional Designer · Curriculum Specialist",
      biography: "An instructional designer developing structured curricular materials.",
      creatorTypes: ["educator"],
      specialties: ["Curriculum Design"],
      topics: ["Education"],
      languages: ["English"],
      intendedFormats: ["course"],
      isFeatured: false,
      applicationStatus: "approved",
      profileStatus: "approved",
      isPublic: false,
      moduleOrder: ["courses", "about"],
    },
    {
      key: "workflow-more-info-applicant",
      slug: "workflow-dev-rao",
      displayName: "Dev Rao",
      headline: "Software practitioner sharing responsible engineering lessons",
      biography: "Dev documents software decisions and the operational lessons behind them.",
      creatorTypes: ["specialist"],
      specialties: ["Software engineering"],
      topics: ["Technology"],
      languages: ["English"],
      intendedFormats: ["article", "course"],
      isFeatured: false,
      applicationStatus: "more_info_required",
      profileStatus: null,
      isPublic: false,
      moduleOrder: ["articles", "about"],
    },
  ],

  topics: [
    { name: "Coding", slug: "coding", description: "Modern web development, algorithms, and engineering fundamentals." },
    { name: "Software Development", slug: "software-development", description: "Building reliable, maintainable software systems." },
    { name: "JavaScript", slug: "javascript", description: "Modern JavaScript language features and asynchronous programming." },
    { name: "React", slug: "react", description: "Component architecture, hooks, and modern React patterns." },
    { name: "SAP", slug: "sap", description: "Enterprise ERP architecture, financial accounting, and integration." },
    { name: "Government Exams", slug: "government-exams", description: "Concept clarity and quantitative problem solving for exam preparation." },
    { name: "Career", slug: "career", description: "Professional growth, career transitions, and workplace communication." },
    { name: "Business", slug: "business", description: "Practical decision-making, entrepreneurship, and product thinking." },
    { name: "Personal Finance", slug: "personal-finance", description: "Practical budgeting, saving strategies, and financial organization." },
    { name: "Design", slug: "design", description: "UI design fundamentals, visual hierarchy, and design systems." },
    { name: "Communication", slug: "communication", description: "Clear speaking, professional English, and presentation confidence." },
    { name: "Languages", slug: "languages", description: "Practical language acquisition and everyday usage." },
    { name: "Motivation", slug: "motivation", description: "Sustainable habits, handling setbacks, and intentional reflection." },
    { name: "Personal Growth", slug: "personal-growth", description: "Continuous self-improvement, resilience, and life transitions." },
    { name: "Data Analytics", slug: "data-analytics", description: "SQL querying, business intelligence, and data-driven insights." },
    { name: "Travel", slug: "travel", description: "Perspectives on journeys, places, and turning points." },
    { name: "Life", slug: "life", description: "Essays on human experience, relationships, and reflection." },
    { name: "Education", slug: "education", description: "Learning strategies, knowledge retention, and study design." },
    { name: "Creative Practice", slug: "creative-practice", description: "Writing, storytelling, and building a creative body of work." },
    { name: "Technology", slug: "technology", description: "Responsible technical knowledge and digital literacy." },
    { name: "Relationships", slug: "relationships", description: "Connection, empathy, and interpersonal dynamics." },
  ],

  content: [
    // 1. Priya Sharma
    {
      key: "course-react-fundamentals",
      owner: "priya-sharma",
      contentType: "course",
      title: "React Fundamentals",
      slug: "react-fundamentals",
      subtitle: "Build a strong foundation in modern component architecture",
      description: "Build a strong foundation in React by understanding components, props, state, and the ideas behind modern React applications.",
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "beginner",
      language: "English",
      estimatedDurationMinutes: 180,
      learningOutcomes: ["Understand React component hierarchy", "Manage local state predictably", "Work effectively with props and events"],
      modules: [
        {
          stableKey: "mod-react-get-started",
          title: "Module 1 — Getting Started",
          description: "Introduction to React philosophy and toolchains.",
          order: 0,
          lessons: [
            {
              stableKey: "les-what-is-react",
              title: "Lesson 1 — What is React?",
              description: "The core ideas of declarative UI and virtual DOM.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "React is a JavaScript library for building user interfaces. Instead of manually manipulating the DOM, you describe what your UI should look like for a given state.",
            },
            {
              stableKey: "les-setting-up-react",
              title: "Lesson 2 — Setting Up a React Project",
              description: "Fast project bootstrapping using Vite.",
              lessonType: "text",
              order: 1,
              isPreview: false,
              body: "Modern React applications typically start with Vite or a lightweight framework. In this lesson, we configure our initial development environment.",
            },
          ],
        },
        {
          stableKey: "mod-react-components",
          title: "Module 2 — Components",
          description: "Decomposing interfaces into reusable building blocks.",
          order: 1,
          lessons: [
            {
              stableKey: "les-understanding-components",
              title: "Lesson 3 — Understanding Components",
              description: "Function components and JSX return values.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Components are independent, reusable pieces of UI. They accept arbitrary inputs called props and return React elements describing what should appear on screen.",
            },
            {
              stableKey: "les-working-with-props",
              title: "Lesson 4 — Working with Props",
              description: "Passing data down the component tree.",
              lessonType: "text",
              order: 1,
              isPreview: false,
              body: "Props are read-only attributes passed from parent to child. Keeping props pure ensures that your component rendering remains deterministic.",
            },
          ],
        },
        {
          stableKey: "mod-react-state",
          title: "Module 3 — State",
          description: "Managing dynamic and interactive data.",
          order: 2,
          lessons: [
            {
              stableKey: "les-intro-to-state",
              title: "Lesson 5 — Introduction to State",
              description: "The useState hook and component lifecycle.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "State is a component's personal memory. When state updates, React automatically schedules a re-render to reflect the new state in the DOM.",
            },
            {
              stableKey: "les-updating-state-safely",
              title: "Lesson 6 — Updating State Safely",
              description: "Immutability and functional state updates.",
              lessonType: "text",
              order: 1,
              isPreview: false,
              body: "Never mutate state variables directly. Always use the setter function and provide a callback when the new state depends on previous state.",
            },
          ],
        },
      ],
    },
    {
      key: "article-what-react-components-are",
      owner: "priya-sharma",
      contentType: "article",
      title: "What React Components Really Are",
      slug: "what-react-components-really-are",
      description: "A deep dive into how function components transform data into interface trees.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Coding",
      body: "<p>At their core, React components are simply JavaScript functions that accept inputs and return element descriptions. When you strip away the syntax sugar of JSX, a component is a predictable transformation of state into virtual DOM nodes.</p><p>Understanding this mental model eliminates much of the confusion around re-renders, hooks, and component boundaries.</p>",
    },
    {
      key: "article-first-reusable-react-component",
      owner: "priya-sharma",
      contentType: "article",
      title: "Build Your First Reusable React Component",
      slug: "build-your-first-reusable-react-component",
      description: "Step-by-step tutorial on designing clean, reusable interface primitives.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Coding",
      body: "<p>When building interface primitives like Buttons or Badges, separating styling, layout props, and event handlers ensures the component remains flexible across different application contexts.</p><p>In this guide, we construct a resilient Button component with variant, size, and disabled states.</p>",
    },
    {
      key: "resource-react-components-ref",
      owner: "priya-sharma",
      contentType: "resource",
      title: "React Components Reference",
      slug: "react-components-reference",
      description: "Quick reference card for common React hook signatures and component patterns.",
      resourceType: "pdf",
      sizeBytes: 102400,
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
    },
    {
      key: "video-virtual-dom-explained",
      owner: "priya-sharma",
      contentType: "video",
      title: "Understanding the Virtual DOM",
      slug: "understanding-the-virtual-dom",
      description: "Visual walkthrough of reconciliation and diffing algorithms in React.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      language: "English",
      durationSeconds: 480,
    },

    // 2. Arun Mehta
    {
      key: "course-sap-fico-foundations",
      owner: "arun-mehta",
      contentType: "course",
      title: "SAP FICO Foundations",
      slug: "sap-fico-foundations",
      subtitle: "Master the fundamental modules of SAP Financial Accounting and Controlling",
      description: "An enterprise-systems course explaining SAP financial processes through practical business scenarios, process maps, and structured learning paths.",
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "beginner",
      language: "English",
      estimatedDurationMinutes: 240,
      learningOutcomes: ["Understand SAP ERP enterprise hierarchy", "Configure company codes and chart of accounts", "Execute core General Ledger and Accounts Payable transactions"],
      modules: [
        {
          stableKey: "mod-sap-intro",
          title: "Module 1 — Introduction to SAP",
          description: "High-level overview of SAP ERP and S/4HANA architecture.",
          order: 0,
          lessons: [
            {
              stableKey: "les-sap-overview",
              title: "Lesson 1 — Overview of SAP ERP",
              description: "Understanding enterprise business suites and integration points.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "SAP connects sales, procurement, production, and accounting into one centralized system. In this lesson, we explore how business events trigger automated financial postings.",
            },
          ],
        },
        {
          stableKey: "mod-sap-structure",
          title: "Module 2 — Enterprise Structure",
          description: "Defining organizational units in financial accounting.",
          order: 1,
          lessons: [
            {
              stableKey: "les-company-codes-org",
              title: "Lesson 2 — Defining Organizational Units",
              description: "Client, Company Code, Business Area, and Credit Control Area.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "The Company Code is the smallest organizational unit for which an independent set of financial statements can be generated.",
            },
          ],
        },
        {
          stableKey: "mod-sap-gl",
          title: "Module 3 — General Ledger Basics",
          description: "Chart of accounts, posting keys, and fiscal year variants.",
          order: 2,
          lessons: [
            {
              stableKey: "les-gl-chart-accounts",
              title: "Lesson 3 — Chart of Accounts & GL Master",
              description: "Structure of operational and country-specific charts of accounts.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "The General Ledger master record contains account control data at the Chart of Accounts level and Company Code specific segment.",
            },
          ],
        },
        {
          stableKey: "mod-sap-ap",
          title: "Module 4 — Accounts Payable Overview",
          description: "Vendor master management and invoice verification.",
          order: 3,
          lessons: [
            {
              stableKey: "les-ap-vendor-invoices",
              title: "Lesson 4 — Vendor Invoices and Payments",
              description: "Processing vendor invoices and automatic payment program execution.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Accounts Payable manages vendor accounting data, matching purchase orders, goods receipts, and vendor invoices.",
            },
          ],
        },
      ],
    },
    {
      key: "article-understanding-company-codes",
      owner: "arun-mehta",
      contentType: "article",
      title: "Understanding Company Codes in SAP",
      slug: "understanding-company-codes-in-sap",
      description: "How multinational enterprises structure legal entities within SAP FICO.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Professional Skills",
      body: "<p>A Company Code in SAP represents an independent accounting unit capable of producing a balance sheet and profit-and-loss statement. In multinational implementations, choosing whether to represent a subsidiary as a company code or a business area is one of the most consequential architectural decisions.</p>",
    },
    {
      key: "resource-sap-fico-process-map",
      owner: "arun-mehta",
      contentType: "resource",
      title: "SAP FICO Process Map",
      slug: "sap-fico-process-map",
      description: "Visual workflow diagram connecting Procure-to-Pay and Order-to-Cash with GL postings.",
      resourceType: "document",
      sizeBytes: 245000,
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
    },

    // 3. Ravi Menon
    {
      key: "course-quantitative-aptitude",
      owner: "ravi-menon",
      contentType: "course",
      title: "Quantitative Aptitude Foundations",
      slug: "quantitative-aptitude-foundations",
      subtitle: "Speed, accuracy, and core mental math for competitive examinations",
      description: "An exam-preparation course focused on concept clarity, timed practice, problem-solving strategies, and structured revision.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "all_levels",
      language: "English",
      estimatedDurationMinutes: 200,
      learningOutcomes: ["Master percentage-to-fraction conversions", "Solve ratio and proportion problems without equations", "Apply unitary method to time and work problems"],
      modules: [
        {
          stableKey: "mod-apt-percentages",
          title: "Module 1 — Percentages",
          description: "Fraction equivalencies, percentage changes, and successive discounts.",
          order: 0,
          lessons: [
            {
              stableKey: "les-percentage-shortcuts",
              title: "Lesson 1 — Percentage Shortcuts & Mental Math",
              description: "Memorizing key fraction conversions for rapid calculation.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "Converting percentages to standard fractions (like 16.66% = 1/6 or 14.28% = 1/7) allows you to solve complex multi-step problems mentally in under 30 seconds.",
            },
          ],
        },
        {
          stableKey: "mod-apt-ratio",
          title: "Module 2 — Ratio and Proportion",
          description: "Compounded ratios, proportional division, and mixture problems.",
          order: 1,
          lessons: [
            {
              stableKey: "les-ratio-variations",
              title: "Lesson 2 — Direct and Inverse Variations",
              description: "Solving cross-multiplication without algebraic overhead.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "When quantities change proportionally, scaling factors allow you to bypass long equations. We examine standard exam question archetypes.",
            },
          ],
        },
        {
          stableKey: "mod-apt-profit-loss",
          title: "Module 3 — Profit and Loss",
          description: "Marked price, cost price, selling price, and discount calculations.",
          order: 2,
          lessons: [
            {
              stableKey: "les-profit-margin-calc",
              title: "Lesson 3 — Cost Price, Selling Price, and Margin",
              description: "Understanding multiplier notation in commercial math.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Expressing profit margin as a multiplier on cost price prevents common errors when discounts and sales taxes are combined.",
            },
          ],
        },
        {
          stableKey: "mod-apt-time-work",
          title: "Module 4 — Time and Work",
          description: "LCM method for pipes, cisterns, and collaborative work rates.",
          order: 3,
          lessons: [
            {
              stableKey: "les-efficiency-work-eq",
              title: "Lesson 4 — Efficiency and Work Equations",
              description: "The total units of work approach using LCM.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "By assigning total work equal to the LCM of individual completion times, each person's contribution becomes an integer rate per day.",
            },
          ],
        },
      ],
    },
    {
      key: "resource-aptitude-formula-sheet",
      owner: "ravi-menon",
      contentType: "resource",
      title: "Aptitude Formula Revision Sheet",
      slug: "aptitude-formula-revision-sheet",
      description: "Complete formula summary covering arithmetic, algebra, and geometry for quick exam revision.",
      resourceType: "pdf",
      sizeBytes: 156000,
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
    },

    // 4. Maya Thomas
    {
      key: "story-city-almost-left-behind",
      owner: "maya-thomas",
      contentType: "story",
      title: "The City I Almost Left Behind",
      slug: "the-city-i-almost-left-behind",
      description: "A reflective narrative about staying in a changing city when leaving seemed like the easier choice.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Life",
      storyLayout: "chapter-journey",
      storySections: [
        {
          id: "sec-city-ch1",
          type: "chapter",
          chapterNumber: "1",
          chapterTitle: "The Packed Boxes",
          heading: "The Packed Boxes",
          body: "The cardboard boxes were already taped shut by the doorway when the first monsoon rain began to tap rhythmically against the windowpane. I had spent six months preparing to move, convincing myself that a new postal code was the only way to begin again.",
        },
        {
          id: "sec-city-reflection",
          type: "reflection",
          heading: "A Moment of Pause",
          body: "Sometimes we mistake the exhaustion of a difficult year for a dissatisfaction with the place itself. Standing there in the hallway, the familiar smell of wet asphalt made me reconsider what I was actually trying to leave.",
        },
        {
          id: "sec-city-ch2",
          type: "chapter",
          chapterNumber: "2",
          chapterTitle: "Unpacking the Future",
          heading: "Unpacking the Future",
          body: "Unpacking took less than an hour, but the feeling of relief lasted for years. A city does not owe us meaning; we cultivate meaning by showing up consistently for the people and corners that make it home.",
        },
      ],
    },
    {
      key: "story-train-ride-remember",
      owner: "maya-thomas",
      contentType: "story",
      title: "A Train Ride I Still Remember",
      slug: "a-train-ride-i-still-remember",
      description: "Conversations with strangers along a twenty-four hour journey across the Western Ghats.",
      accessLevel: "premium",
      workflowStatus: "published",
      category: "Travel",
      storyLayout: "classic-reader",
      storySections: [
        {
          id: "sec-train-1",
          type: "text",
          heading: "The Rhythm of the Rails",
          body: "Long train journeys create a peculiar form of intimacy. Strangers share tea, newspapers, and life histories that they would never recount to their closest acquaintances at home.",
        },
        {
          id: "sec-train-quote",
          type: "quote",
          quote: "The destination is only an excuse for the conversations you would otherwise never have had.",
          attribution: "Maya Thomas",
        },
        {
          id: "sec-train-2",
          type: "text",
          heading: "The Western Ghats at Dawn",
          body: "As mist cleared from the valleys, the carriage fell silent. Everyone was watching the green slopes pass, momentarily united in quiet appreciation.",
        },
      ],
    },
    {
      key: "article-what-travel-teaches-us",
      owner: "maya-thomas",
      contentType: "article",
      title: "What Travel Teaches Us About Coming Home",
      slug: "what-travel-teaches-us-about-coming-home",
      description: "Why the most transformative part of any journey is returning to familiar routines with fresh eyes.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Travel",
      body: "<p>We often measure travel by the novelty of foreign landscapes, but its true utility lies in defamiliarizing our daily routine. When you return home after weeks away, the kettle on your stove and the quiet of your room feel like discoveries rather than defaults.</p>",
    },

    // 5. Neha Kapoor
    {
      key: "podcast-the-career-journey",
      owner: "neha-kapoor",
      contentType: "podcast",
      title: "The Career Journey",
      slug: "the-career-journey",
      description: "Honest conversations on career transitions, workplace dynamics, and building meaningful professional trajectories.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      language: "English",
      episodes: [
        {
          slug: "how-to-choose-your-first-direction",
          title: "How to Choose Your First Direction",
          description: "Navigating the overwhelming choices facing early-career professionals.",
          episodeNumber: 1,
          seasonNumber: 1,
          durationSeconds: 1680,
          accessLevel: "free",
          showNotes: "In this episode, we break down why finding the 'perfect' first job is a myth and how focusing on transferable skills builds optionality.",
        },
        {
          slug: "when-your-career-plan-changes",
          title: "When Your Career Plan Changes",
          description: "How to pivot gracefully when industry trends or personal priorities shift.",
          episodeNumber: 2,
          seasonNumber: 1,
          durationSeconds: 1920,
          accessLevel: "free",
          showNotes: "Practical steps for auditing your network, rebranding your experience, and speaking confidently about career shifts.",
        },
        {
          slug: "preparing-for-better-interviews",
          title: "Preparing for Better Interviews",
          description: "Frameworks for storytelling and structured communication during job interviews.",
          episodeNumber: 3,
          seasonNumber: 1,
          durationSeconds: 2100,
          accessLevel: "premium",
          showNotes: "Deep-dive workshop covering the STAR method, handling behavioral curves, and negotiating offers effectively.",
        },
      ],
    },
    {
      key: "article-career-without-perfect-plan",
      owner: "neha-kapoor",
      contentType: "article",
      title: "Building a Career Without a Perfect Plan",
      slug: "building-a-career-without-a-perfect-plan",
      description: "Why adaptability and skill compounding beat rigid five-year career plans.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Career",
      body: "<p>The myth of the linear career path creates unnecessary anxiety for graduates and early professionals. Real professional growth happens through adjacent opportunities: mastering one skill deeply until it exposes you to related challenges.</p>",
    },
    {
      key: "course-navigating-workplace-transitions",
      owner: "neha-kapoor",
      contentType: "course",
      title: "Navigating Workplace Transitions",
      slug: "navigating-workplace-transitions",
      subtitle: "Strategies for joining new teams, managing expectations, and establishing credibility",
      description: "A practical guide for early professionals stepping into new roles and unfamiliar workplace cultures.",
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "intermediate",
      language: "English",
      estimatedDurationMinutes: 120,
      learningOutcomes: ["Build a 30-60-90 day onboarding plan", "Communicate progress effectively with managers", "Navigate team dynamics and cross-functional alignment"],
      modules: [
        {
          stableKey: "mod-work-first90",
          title: "Module 1 — The First 90 Days",
          description: "Establishing momentum and learning organizational context.",
          order: 0,
          lessons: [
            {
              stableKey: "les-listening-tour",
              title: "Lesson 1 — Conducting a Stakeholder Listening Tour",
              description: "Asking the right questions during your first month.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "During your first four weeks, prioritize understanding team history, active bottlenecks, and key stakeholder expectations before suggesting major changes.",
            },
          ],
        },
        {
          stableKey: "mod-work-alignment",
          title: "Module 2 — Managing Up and Across",
          description: "Structured communication and periodic status alignment.",
          order: 1,
          lessons: [
            {
              stableKey: "les-effective-status",
              title: "Lesson 2 — Effective Status Updates",
              description: "Writing concise weekly updates that highlight progress and blockers.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "A structured update formats items into Done, Next, and Blocked, giving leadership immediate clarity on project velocity.",
            },
          ],
        },
      ],
    },

    // 6. Karan Iyer
    {
      key: "course-business-fundamentals",
      owner: "karan-iyer",
      contentType: "course",
      title: "Business Fundamentals for First-Time Founders",
      slug: "business-fundamentals-for-first-time-founders",
      subtitle: "Validating ideas, understanding unit economics, and building sustainable business models",
      description: "A business educator course focused on practical decision-making, customer understanding, sustainable growth, and turning ideas into testable products.",
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "beginner",
      language: "English",
      estimatedDurationMinutes: 150,
      learningOutcomes: ["Formulate testable value propositions", "Calculate unit economics and contribution margins", "Conduct unbiased customer discovery interviews"],
      modules: [
        {
          stableKey: "mod-biz-discovery",
          title: "Module 1 — Customer Discovery",
          description: "Validating customer problems before writing code.",
          order: 0,
          lessons: [
            {
              stableKey: "les-identifying-real-problems",
              title: "Lesson 1 — Identifying Real Problems",
              description: "Distinguishing between nice-to-have features and mission-critical pain points.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "Customers rarely articulate their problems directly in terms of solutions. By observing existing workarounds, founders discover genuine market willingness to pay.",
            },
          ],
        },
        {
          stableKey: "mod-biz-economics",
          title: "Module 2 — Business Economics",
          description: "Customer acquisition cost, lifetime value, and margins.",
          order: 1,
          lessons: [
            {
              stableKey: "les-unit-economics",
              title: "Lesson 2 — Unit Economics & Pricing",
              description: "Structuring margins that support sustainable growth.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "A product is only viable if the cost to acquire and serve a customer is significantly lower than the revenue generated over their lifetime.",
            },
          ],
        },
      ],
    },
    {
      key: "article-start-with-customer",
      owner: "karan-iyer",
      contentType: "article",
      title: "Start With the Customer, Not the Product",
      slug: "start-with-the-customer-not-the-product",
      description: "Why most startup failures stem from building products nobody asked for.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Business",
      body: "<p>The most common failure mode in entrepreneurship is falling in love with a technical solution before deeply understanding the customer's operational reality. Start with conversations, observation, and manual workflows.</p>",
    },
    {
      key: "article-test-idea-before-building",
      owner: "karan-iyer",
      contentType: "article",
      title: "How to Test an Idea Before Building It",
      slug: "how-to-test-an-idea-before-building-it",
      description: "Practical smoke tests, concierge MVPs, and landing page experiments.",
      accessLevel: "premium",
      workflowStatus: "published",
      category: "Business",
      body: "<p>Before investing months into engineering, run lightweight validation tests: manual service delivery, landing pages with intent forms, and pre-order interest. Evidence of intent is worth ten opinions.</p>",
    },
    {
      key: "resource-biz-validation-sheet",
      owner: "karan-iyer",
      contentType: "resource",
      title: "Simple Business Validation Worksheet",
      slug: "simple-business-validation-worksheet",
      description: "Step-by-step matrix for scoring market demand, competition, and distribution channels.",
      resourceType: "spreadsheet",
      sizeBytes: 78000,
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
    },

    // 7. Ananya Rao
    {
      key: "course-personal-budget",
      owner: "ananya-rao",
      contentType: "course",
      title: "Build Your First Personal Budget",
      slug: "build-your-first-personal-budget",
      subtitle: "A realistic, non-restrictive approach to managing income and expenses",
      description: "A personal-finance course focused on budgeting, saving, financial organization, and practical money habits without complicated jargon.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "beginner",
      language: "English",
      estimatedDurationMinutes: 90,
      learningOutcomes: ["Map fixed vs variable expenses accurately", "Implement a zero-based cashflow routine", "Establish a sustainable emergency reserve"],
      modules: [
        {
          stableKey: "mod-fin-baseline",
          title: "Module 1 — Income and Expense Mapping",
          description: "Understanding your current spending patterns without judgment.",
          order: 0,
          lessons: [
            {
              stableKey: "les-cashflow-baseline",
              title: "Lesson 1 — Establishing a Cashflow Baseline",
              description: "Auditing bank statements over the past 90 days.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "A budget is not about deprivation; it is simply an intentional plan for your money. Begin by gathering three months of transaction records to see real patterns.",
            },
          ],
        },
        {
          stableKey: "mod-fin-allocation",
          title: "Module 2 — The Zero-Based Budget",
          description: "Giving every rupee a specific purpose.",
          order: 1,
          lessons: [
            {
              stableKey: "les-allocating-cashflow",
              title: "Lesson 2 — Allocating Every Rupee",
              description: "Dividing income into essentials, goals, and flexible spending.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "When income minus planned expenditures equals zero, you eliminate unintentional money leakage while maintaining flexibility for discretionary enjoyment.",
            },
          ],
        },
      ],
    },
    {
      key: "article-monthly-money-review",
      owner: "ananya-rao",
      contentType: "article",
      title: "A Simple Monthly Money Review",
      slug: "a-simple-monthly-money-review",
      description: "A 20-minute monthly routine to review accounts, spot leaks, and reset goals.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Personal Finance",
      body: "<p>Tracking spending every day often leads to burnout. Instead, conduct a structured 20-minute review on the first of each month to compare budgeted allocations against actual balances.</p>",
    },
    {
      key: "article-tracking-vs-restricting",
      owner: "ananya-rao",
      contentType: "article",
      title: "Why Tracking Spending Is Different From Restricting It",
      slug: "why-tracking-spending-is-different-from-restricting-it",
      description: "How awareness alone changes purchasing behavior without rigid rules.",
      accessLevel: "premium",
      workflowStatus: "published",
      category: "Personal Finance",
      body: "<p>Most financial resolutions fail because they rely entirely on willpower. When you cultivate quiet awareness of spending without moralizing each purchase, decisions naturally align with your values.</p>",
    },
    {
      key: "resource-monthly-budget-worksheet",
      owner: "ananya-rao",
      contentType: "resource",
      title: "Monthly Budget Worksheet",
      slug: "monthly-budget-worksheet",
      description: "Simple printable and spreadsheet template for monthly household budgeting.",
      resourceType: "spreadsheet",
      sizeBytes: 64000,
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
    },

    // 8. Aisha Khan
    {
      key: "course-ui-foundations",
      owner: "aisha-khan",
      contentType: "course",
      title: "UI Foundations: From Layout to Visual Hierarchy",
      slug: "ui-foundations",
      subtitle: "Master grid systems, typography scales, spacing tokens, and visual contrast",
      description: "A design educator course teaching practical interface thinking, UX fundamentals, visual hierarchy, and reusable product-design systems.",
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "beginner",
      language: "English",
      estimatedDurationMinutes: 210,
      learningOutcomes: ["Apply consistent 8pt spatial scales", "Select typographic pairings with readable scales", "Design accessible contrast ratios across dark and light modes"],
      modules: [
        {
          stableKey: "mod-ui-layout",
          title: "Module 1 — Layout",
          description: "Column grids, container constraints, and alignment.",
          order: 0,
          lessons: [
            {
              stableKey: "les-grid-alignment",
              title: "Lesson 1 — Grid Systems and Alignment",
              description: "Using responsive column and baseline grids.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "Strong alignment is the foundation of interface clarity. When elements share common vertical axes, the user's eye scans content with minimal cognitive effort.",
            },
          ],
        },
        {
          stableKey: "mod-ui-spacing",
          title: "Module 2 — Spacing",
          description: "Mathematical spacing scales and whitespace balance.",
          order: 1,
          lessons: [
            {
              stableKey: "les-spatial-rhythm",
              title: "Lesson 2 — Consistent Spatial Rhythm",
              description: "Implementing an 8-point spatial system across UI components.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Using a geometric spacing scale (4, 8, 16, 24, 32, 48, 64px) ensures visual consistency and speeds up collaboration with engineering teams.",
            },
          ],
        },
        {
          stableKey: "mod-ui-typography",
          title: "Module 3 — Typography",
          description: "Font hierarchy, line heights, and optical readability.",
          order: 2,
          lessons: [
            {
              stableKey: "les-type-hierarchy",
              title: "Lesson 3 — Hierarchy and Readability",
              description: "Setting proportional line heights and font weights.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Typography communicates importance. Limiting your interface to two typeface families and a strict size scale creates an orderly visual progression.",
            },
          ],
        },
        {
          stableKey: "mod-ui-contrast",
          title: "Module 4 — Visual Hierarchy",
          description: "Directing user attention through contrast and elevation.",
          order: 3,
          lessons: [
            {
              stableKey: "les-contrast-focal",
              title: "Lesson 4 — Contrast and Focal Points",
              description: "Using luminance, weight, and position to highlight primary actions.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "If every element shouts for attention, none of them will be heard. Design screens with a single primary focal point.",
            },
          ],
        },
      ],
    },
    {
      key: "article-why-good-interfaces-feel-calm",
      owner: "aisha-khan",
      contentType: "article",
      title: "Why Good Interfaces Feel Calm",
      slug: "why-good-interfaces-feel-calm",
      description: "How restrained color palettes, generous whitespace, and subtle feedback reduce user cognitive fatigue.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Design",
      body: "<p>The best digital tools rarely draw attention to their own styling. By reducing visual noise, adhering to established conventions, and respecting user attention, designers create software that feels effortless.</p>",
    },
    {
      key: "resource-ui-review-checklist",
      owner: "aisha-khan",
      contentType: "resource",
      title: "UI Review Checklist",
      slug: "ui-review-checklist",
      description: "Comprehensive 25-point audit guide for design systems and accessibility compliance.",
      resourceType: "document",
      sizeBytes: 112000,
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
    },

    // 9. Daniel Joseph
    {
      key: "course-professional-english",
      owner: "daniel-joseph",
      contentType: "course",
      title: "Everyday Professional English",
      slug: "everyday-professional-english",
      subtitle: "Speak clearly, structure ideas confidently, and improve everyday workplace communication",
      description: "A communication course helping learners speak more clearly, structure ideas confidently, and improve everyday professional English.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "all_levels",
      language: "English",
      estimatedDurationMinutes: 140,
      learningOutcomes: ["Structure concise spoken updates", "Participate actively in workplace meetings", "Deliver structured presentations with confident pacing"],
      modules: [
        {
          stableKey: "mod-eng-intro",
          title: "Module 1 — Introductions",
          description: "Making concise, confident professional introductions.",
          order: 0,
          lessons: [
            {
              stableKey: "les-confident-intro",
              title: "Lesson 1 — Clear and Confident Introductions",
              description: "Crafting a 30-second summary of your role and focus.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "A great professional introduction connects what you do with the outcome it provides, avoiding internal organizational jargon.",
            },
          ],
        },
        {
          stableKey: "mod-eng-conversations",
          title: "Module 2 — Workplace Conversations",
          description: "Active listening and constructive small talk.",
          order: 1,
          lessons: [
            {
              stableKey: "les-active-listening",
              title: "Lesson 2 — Active Listening & Transitions",
              description: "Paraphrasing and bridging conversations smoothly.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Acknowledging what someone said before sharing your perspective builds trust and ensures productive cross-cultural collaboration.",
            },
          ],
        },
        {
          stableKey: "mod-eng-meetings",
          title: "Module 3 — Meetings",
          description: "Interrupting politely and clarifying action items.",
          order: 2,
          lessons: [
            {
              stableKey: "les-meeting-interventions",
              title: "Lesson 3 — Interventions and Structuring Points",
              description: "Using the Rule of Three when summarizing arguments.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "When contributing in large meetings, lead with your conclusion first, followed by your supporting rationale.",
            },
          ],
        },
        {
          stableKey: "mod-eng-presentations",
          title: "Module 4 — Presentations",
          description: "Hooking an audience and managing question-and-answer periods.",
          order: 3,
          lessons: [
            {
              stableKey: "les-presentation-hooks",
              title: "Lesson 4 — Opening Hooks and Transitions",
              description: "Opening strong and closing with clear next steps.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Start presentations with a compelling question or real-world example rather than an agenda slide.",
            },
          ],
        },
      ],
    },
    {
      key: "video-speaking-under-pressure",
      owner: "daniel-joseph",
      contentType: "video",
      title: "Speaking Clearly Under Pressure",
      slug: "speaking-clearly-under-pressure",
      description: "Techniques for managing nervous pacing, vocal projection, and impromptu questions.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      language: "English",
      durationSeconds: 360,
    },
    {
      key: "resource-phrase-guide",
      owner: "daniel-joseph",
      contentType: "resource",
      title: "Professional English Phrase Guide",
      slug: "professional-english-phrase-guide",
      description: "Quick-lookup reference handbook of polite, assertive workplace phrasing.",
      resourceType: "pdf",
      sizeBytes: 180000,
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
    },

    // 10. Meera Nair
    {
      key: "podcast-the-next-chapter",
      owner: "meera-nair",
      contentType: "podcast",
      title: "The Next Chapter",
      slug: "the-next-chapter",
      description: "Reflections on resilience, personal transitions, and finding clarity through life's unexpected turns.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      language: "English",
      episodes: [
        {
          slug: "starting-again",
          title: "Starting Again",
          description: "Letting go of sunken time and embracing new beginnings with patience.",
          episodeNumber: 1,
          seasonNumber: 1,
          durationSeconds: 1540,
          accessLevel: "free",
          showNotes: "Why starting over does not mean losing past experience, and how to frame transitions positively.",
        },
        {
          slug: "staying-consistent",
          title: "Staying Consistent",
          description: "Building quiet daily habits when motivation wavers.",
          episodeNumber: 2,
          seasonNumber: 1,
          durationSeconds: 1620,
          accessLevel: "free",
          showNotes: "Practical habit loops and lowering friction for the actions that matter most.",
        },
        {
          slug: "learning-from-a-difficult-month",
          title: "Learning From a Difficult Month",
          description: "Conducting a gentle, honest post-mortem after personal setbacks.",
          episodeNumber: 3,
          seasonNumber: 1,
          durationSeconds: 1800,
          accessLevel: "premium",
          showNotes: "How to extract lessons from difficult periods without spiraling into self-criticism.",
        },
      ],
    },
    {
      key: "article-motivation-vs-momentum",
      owner: "meera-nair",
      contentType: "article",
      title: "Motivation Is Not the Same as Momentum",
      slug: "motivation-is-not-the-same-as-momentum",
      description: "Why waiting for inspiration is unreliable, and how tiny completed actions create lasting momentum.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Personal Growth",
      body: "<p>Motivation is an emotion that fluctuates based on sleep, weather, and circumstance. Momentum, by contrast, is a physical property generated by completing small, unambiguous tasks day after day.</p>",
    },
    {
      key: "article-starting-again",
      owner: "meera-nair",
      contentType: "article",
      title: "Starting Again Without Starting Over",
      slug: "starting-again-without-starting-over",
      description: "How to recognize the transferable wisdom you carry into each new chapter of life.",
      accessLevel: "premium",
      workflowStatus: "published",
      category: "Personal Growth",
      body: "<p>When a career path, project, or relationship ends, we often feel as though the clock has reset to zero. But you never start over from scratch; you start from experience, with greater self-knowledge than before.</p>",
    },

    // 11. Vikram Sen
    {
      key: "course-sql-data-analysis",
      owner: "vikram-sen",
      contentType: "course",
      title: "SQL for Data Analysis",
      slug: "sql-for-data-analysis",
      subtitle: "From basic SELECT queries to multi-table joins and analytical aggregation",
      description: "A hands-on course covering practical SQL queries, data exploration techniques, and analytical problem-solving for business datasets.",
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "intermediate",
      language: "English",
      estimatedDurationMinutes: 190,
      learningOutcomes: ["Filter and sort large datasets with WHERE and ORDER BY", "Aggregate metrics using GROUP BY and HAVING clauses", "Combine tables reliably using INNER and LEFT JOINs"],
      modules: [
        {
          stableKey: "mod-sql-select",
          title: "Module 1 — SELECT Basics",
          description: "Querying specific attributes, aliasing, and calculating expressions.",
          order: 0,
          lessons: [
            {
              stableKey: "les-sql-select-cols",
              title: "Lesson 1 — Selecting Columns and Aliases",
              description: "The anatomy of a basic SQL query.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "The SELECT statement instructs the query engine which columns to retrieve. Renaming columns with aliases makes downstream reports easier to read.",
            },
          ],
        },
        {
          stableKey: "mod-sql-filter",
          title: "Module 2 — Filtering Data",
          description: "Comparison operators, pattern matching, and NULL handling.",
          order: 1,
          lessons: [
            {
              stableKey: "les-sql-where-clause",
              title: "Lesson 2 — WHERE, LIKE, and IN Clauses",
              description: "Narrowing query results precisely.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Filtering rows early in the query lifecycle minimizes memory consumption and speeds up analytical execution.",
            },
          ],
        },
        {
          stableKey: "mod-sql-agg",
          title: "Module 3 — Aggregation",
          description: "Summary statistics with COUNT, SUM, AVG, and GROUP BY.",
          order: 2,
          lessons: [
            {
              stableKey: "les-sql-groupby-having",
              title: "Lesson 3 — GROUP BY and HAVING",
              description: "Aggregating metrics across categories and filtering summary outputs.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "GROUP BY partitions data into buckets for aggregation. The HAVING clause acts like a WHERE clause for calculated group summaries.",
            },
          ],
        },
        {
          stableKey: "mod-sql-joins",
          title: "Module 4 — Relational JOINs",
          description: "Relational modeling and combining disparate tables.",
          order: 3,
          lessons: [
            {
              stableKey: "les-sql-joins-types",
              title: "Lesson 4 — INNER, LEFT, and Cross Joins",
              description: "Understanding Venn diagram intersections in relational algebra.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Joins link tables along shared key attributes. Choosing between an INNER and LEFT join determines whether unmatched records are preserved.",
            },
          ],
        },
      ],
    },
    {
      key: "article-first-sql-analysis",
      owner: "vikram-sen",
      contentType: "article",
      title: "Your First SQL Analysis",
      slug: "your-first-sql-analysis",
      description: "A beginner-friendly walkthrough analyzing a real-world e-commerce sales dataset.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Data Analytics",
      body: "<p>When beginning data analysis with SQL, avoid jumping directly into writing complex subqueries. Start with data profiling: understand table schemas, check for duplicate primary keys, and inspect null distributions.</p>",
    },
    {
      key: "resource-sql-query-ref",
      owner: "vikram-sen",
      contentType: "resource",
      title: "SQL Query Reference",
      slug: "sql-query-reference",
      description: "Handy printable cheat-sheet for syntax, window functions, and join types.",
      resourceType: "pdf",
      sizeBytes: 220000,
      accessLevel: "premium",
      workflowStatus: "published",
      publicationStatus: "published",
    },

    // 12. Leena George (Multi-format Creator)
    {
      key: "course-lifelong-learning",
      owner: "leena-george",
      contentType: "course",
      title: "Foundations of Lifelong Learning",
      slug: "foundations-of-lifelong-learning",
      subtitle: "Cultivating mental models, structured synthesis, and durable memory",
      description: "A comprehensive course on effective study methodologies, critical reading, and building a sustainable personal knowledge system.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      level: "all_levels",
      language: "English",
      estimatedDurationMinutes: 160,
      learningOutcomes: ["Construct a personal knowledge notebook", "Apply the Feynman technique to distill complex topics", "Implement spaced repetition systems for active recall"],
      modules: [
        {
          stableKey: "mod-learn-models",
          title: "Module 1 — Mental Models",
          description: "Understanding cognitive frameworks for rapid comprehension.",
          order: 0,
          lessons: [
            {
              stableKey: "les-how-to-learn",
              title: "Lesson 1 — Learning How to Learn",
              description: "Diffused vs focused thinking modes.",
              lessonType: "text",
              order: 0,
              isPreview: true,
              body: "The human brain alternates between focused mode for detailed calculations and diffused mode for conceptual synthesis. Balancing both accelerates mastery.",
            },
          ],
        },
        {
          stableKey: "mod-learn-retention",
          title: "Module 2 — Knowledge Retention",
          description: "Active recall and spaced repetition in daily study.",
          order: 1,
          lessons: [
            {
              stableKey: "les-spaced-rep",
              title: "Lesson 2 — Spaced Repetition in Practice",
              description: "Combatting the forgetting curve through structured review.",
              lessonType: "text",
              order: 0,
              isPreview: false,
              body: "Reviewing concepts at expanding intervals cements short-term working memory into long-term biological neural pathways.",
            },
          ],
        },
      ],
    },
    {
      key: "article-art-of-asking-questions",
      owner: "leena-george",
      contentType: "article",
      title: "The Art of Asking Better Questions",
      slug: "the-art-of-asking-better-questions",
      description: "How inquiry drives discovery and breaks through conventional thinking.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Education",
      body: "<p>Most learning bottlenecks are not caused by an inability to understand answers, but by asking questions framed too narrowly. By stepping back and interrogating underlying assumptions, learners unlock deeper insights.</p>",
    },
    {
      key: "article-deep-work-distracted-world",
      owner: "leena-george",
      contentType: "article",
      title: "Deep Work in a Distracted World",
      slug: "deep-work-in-a-distracted-world",
      description: "Strategies for protecting uninterrupted cognitive blocks in an environment of constant notification.",
      accessLevel: "premium",
      workflowStatus: "published",
      category: "Education",
      body: "<p>The ability to perform deep, focused work is becoming increasingly rare at the exact moment it is becoming most valuable in the modern economy.</p>",
    },
    {
      key: "story-notes-from-decade-reinvention",
      owner: "leena-george",
      contentType: "story",
      title: "Notes from a Decade of Reinvention",
      slug: "notes-from-a-decade-of-reinvention",
      description: "An editorial memoir on switching industries, embracing the beginner mindset, and learning in public.",
      accessLevel: "free",
      workflowStatus: "published",
      category: "Personal Growth",
      storyLayout: "magazine-feature",
      storySections: [
        {
          id: "sec-reinvent-1",
          type: "chapter",
          chapterNumber: "1",
          chapterTitle: "The Beginner's Mind",
          heading: "The Beginner's Mind",
          body: "When you switch fields mid-career, the hardest thing to shed is not your previous skill set, but the ego that came with being considered an expert.",
        },
        {
          id: "sec-reinvent-quote",
          type: "quote",
          quote: "Growth begins the moment you become comfortable looking foolish in pursuit of curiosity.",
          attribution: "Leena George",
        },
        {
          id: "sec-reinvent-2",
          type: "chapter",
          chapterNumber: "2",
          chapterTitle: "Building in Public",
          heading: "Building in Public",
          body: "Publishing notes, essays, and early drafts felt vulnerable at first. But sharing the messy middle attracted collaborators and mentors who shaped my entire trajectory.",
        },
      ],
    },
    {
      key: "podcast-conversations-on-craft",
      owner: "leena-george",
      contentType: "podcast",
      title: "Conversations on Craft",
      slug: "conversations-on-craft",
      description: "In-depth explorations of creative discipline, independent teaching, and sustained productivity.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      language: "English",
      episodes: [
        {
          slug: "curiosity-as-a-strategy",
          title: "Curiosity as a Strategy",
          description: "How following genuine intellectual curiosity creates unique skill intersections.",
          episodeNumber: 1,
          seasonNumber: 1,
          durationSeconds: 1740,
          accessLevel: "free",
          showNotes: "Why cross-disciplinary learners often see solutions that domain specialists miss.",
        },
        {
          slug: "building-habits-that-stick",
          title: "Building Habits That Stick",
          description: "Designing environments that support long-term creative output.",
          episodeNumber: 2,
          seasonNumber: 1,
          durationSeconds: 1890,
          accessLevel: "premium",
          showNotes: "Practical friction design: making good habits obvious and destructive distractions difficult.",
        },
      ],
    },
    {
      key: "resource-learning-toolkit",
      owner: "leena-george",
      contentType: "resource",
      title: "Lifelong Learning Toolkit",
      slug: "lifelong-learning-toolkit",
      description: "Comprehensive guide to note-taking methods, syllabus design, and learning journals.",
      resourceType: "pdf",
      sizeBytes: 195000,
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
    },
    {
      key: "video-daily-learning-routine",
      owner: "leena-george",
      contentType: "video",
      title: "Structuring Your Daily Learning Routine",
      slug: "structuring-your-daily-learning-routine",
      description: "A 30-minute daily framework for reading, note synthesis, and deliberate practice.",
      accessLevel: "free",
      workflowStatus: "published",
      publicationStatus: "published",
      language: "English",
      durationSeconds: 420,
    },
  ],

  exams: [
    {
      key: "exam-general-aptitude",
      owner: "ravi-menon",
      contentType: "exam",
      title: "General Aptitude Practice",
      slug: "general-aptitude-practice",
      description: "Structured syllabus overview and practice problem breakdown for quantitative aptitude.",
      examCategory: "Government Exams",
      jurisdiction: "National",
      subjectLabels: ["Aptitude", "Reasoning", "Quantitative Analysis"],
      accessLevel: "free",
      status: "published",
      assessmentEngineAvailable: false,
    },
  ],

  follows: [
    { creatorKey: "priya-sharma", followerCount: 8 },
    { creatorKey: "arun-mehta", followerCount: 5 },
    { creatorKey: "ravi-menon", followerCount: 7 },
    { creatorKey: "maya-thomas", followerCount: 11 },
    { creatorKey: "neha-kapoor", followerCount: 6 },
    { creatorKey: "karan-iyer", followerCount: 4 },
    { creatorKey: "ananya-rao", followerCount: 9 },
    { creatorKey: "aisha-khan", followerCount: 10 },
    { creatorKey: "daniel-joseph", followerCount: 3 },
    { creatorKey: "meera-nair", followerCount: 8 },
    { creatorKey: "vikram-sen", followerCount: 6 },
    { creatorKey: "leena-george", followerCount: 12 },
  ],

  economy: { active: false, earningsAmount: null, payoutAvailable: false },
});

const assertFixtureEnvironment = (environment = process.env.NODE_ENV) => {
  if (environment === "production") {
    throw Object.assign(new Error("Creator + Learn fixtures cannot run in production."), {
      code: "PRODUCTION_FIXTURES_DISABLED",
    });
  }
  return true;
};

const buildCreatorLearnFixtures = ({ environment = process.env.NODE_ENV } = {}) => {
  assertFixtureEnvironment(environment);
  return JSON.parse(JSON.stringify(DEVELOPMENT_FIXTURES));
};

module.exports = {
  DEVELOPMENT_FIXTURES,
  assertFixtureEnvironment,
  buildCreatorLearnFixtures,
};
