const ROOM_STATUSES = Object.freeze({
  CREATED: "CREATED",
  LOBBY: "LOBBY",
  HOST_SETUP: "HOST_SETUP",
  READY: "READY",
  IN_PROGRESS: "IN_PROGRESS",
  ROUND_REVEAL: "ROUND_REVEAL",
  BETWEEN_ROUNDS: "BETWEEN_ROUNDS",
  FINISHED: "FINISHED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
});

const TERMINAL_ROOM_STATUSES = Object.freeze([
  ROOM_STATUSES.FINISHED,
  ROOM_STATUSES.EXPIRED,
  ROOM_STATUSES.CANCELLED,
]);

const PLAYER_ROLES = Object.freeze({
  HOST: "HOST",
  PLAYER: "PLAYER",
});

const GAME_KEYS = Object.freeze({
  WHO_KNOWS_ME_BETTER: "who-knows-me-better",
  LIFE_AUCTION: "life-auction",
});

const ERROR_CODES = Object.freeze({
  BAD_REQUEST: "MULTIPLAYER_BAD_REQUEST",
  INVALID_TOKEN: "MULTIPLAYER_INVALID_TOKEN",
  ROOM_NOT_FOUND: "MULTIPLAYER_ROOM_NOT_FOUND",
  ROOM_FULL: "MULTIPLAYER_ROOM_FULL",
  ROOM_CLOSED: "MULTIPLAYER_ROOM_CLOSED",
  NICKNAME_TAKEN: "MULTIPLAYER_NICKNAME_TAKEN",
  NICKNAME_BLOCKED: "MULTIPLAYER_NICKNAME_BLOCKED",
  NOT_HOST: "MULTIPLAYER_NOT_HOST",
  INVALID_STATE: "MULTIPLAYER_INVALID_STATE",
  INVALID_ACTION: "MULTIPLAYER_INVALID_ACTION",
  DUPLICATE_ACTION: "MULTIPLAYER_DUPLICATE_ACTION",
  VERSION_CONFLICT: "MULTIPLAYER_VERSION_CONFLICT",
  RATE_LIMITED: "MULTIPLAYER_RATE_LIMITED",
  SERVER_UNAVAILABLE: "MULTIPLAYER_SERVER_UNAVAILABLE",
});

const ROOM_CODE_PATTERN = /^MJ-[A-HJ-NP-Z2-9]{4}$/;

module.exports = {
  ERROR_CODES,
  GAME_KEYS,
  PLAYER_ROLES,
  ROOM_CODE_PATTERN,
  ROOM_STATUSES,
  TERMINAL_ROOM_STATUSES,
};
