const { ERROR_CODES, ROOM_STATUSES } = require("./constants");
const MultiplayerError = require("./MultiplayerError");

const ALLOWED_TRANSITIONS = Object.freeze({
  [ROOM_STATUSES.CREATED]: [ROOM_STATUSES.LOBBY, ROOM_STATUSES.CANCELLED],
  [ROOM_STATUSES.LOBBY]: [ROOM_STATUSES.HOST_SETUP, ROOM_STATUSES.READY, ROOM_STATUSES.CANCELLED, ROOM_STATUSES.EXPIRED],
  [ROOM_STATUSES.HOST_SETUP]: [ROOM_STATUSES.READY, ROOM_STATUSES.LOBBY, ROOM_STATUSES.CANCELLED, ROOM_STATUSES.EXPIRED],
  [ROOM_STATUSES.READY]: [ROOM_STATUSES.LOBBY, ROOM_STATUSES.HOST_SETUP, ROOM_STATUSES.IN_PROGRESS, ROOM_STATUSES.CANCELLED, ROOM_STATUSES.EXPIRED],
  [ROOM_STATUSES.IN_PROGRESS]: [ROOM_STATUSES.ROUND_REVEAL, ROOM_STATUSES.CANCELLED, ROOM_STATUSES.EXPIRED],
  [ROOM_STATUSES.ROUND_REVEAL]: [ROOM_STATUSES.BETWEEN_ROUNDS, ROOM_STATUSES.FINISHED, ROOM_STATUSES.CANCELLED, ROOM_STATUSES.EXPIRED],
  [ROOM_STATUSES.BETWEEN_ROUNDS]: [ROOM_STATUSES.IN_PROGRESS, ROOM_STATUSES.CANCELLED, ROOM_STATUSES.EXPIRED],
  [ROOM_STATUSES.FINISHED]: [ROOM_STATUSES.LOBBY, ROOM_STATUSES.EXPIRED],
  [ROOM_STATUSES.EXPIRED]: [],
  [ROOM_STATUSES.CANCELLED]: [],
});

const assertTransition = (from, to) => {
  if (!ALLOWED_TRANSITIONS[from]?.includes(to)) {
    throw new MultiplayerError(
      ERROR_CODES.INVALID_STATE,
      `Room cannot move from ${from} to ${to}.`,
      { status: 409 }
    );
  }
};

module.exports = { ALLOWED_TRANSITIONS, assertTransition };
