const ALL_CORE = ["classic-life", "random-mix", "chaos"];
const DEEP = ["classic-life", "deep-life", "random-mix", "chaos"];
const FRIENDS = ["friends-night", "random-mix", "chaos"];
const SUCCESS = ["classic-life", "money-success", "random-mix", "chaos"];
const DREAM = ["classic-life", "dream-life", "random-mix", "chaos"];

const lot = ({ id, title, category, icon, basePrice, modes, traits, ...rest }) => Object.freeze({
  id,
  version: 1,
  locale: "en",
  title,
  shortDescription: rest.shortDescription || "A fictional life choice for tonight's auction.",
  category,
  icon,
  visualTheme: rest.visualTheme || category.toLocaleLowerCase("en").replace(/\s+/g, "-"),
  basePrice,
  auctionType: rest.auctionType || "OPEN_ASCENDING",
  modeCompatibility: modes,
  rarity: rest.rarity || "COMMON",
  tone: rest.tone || "WARM",
  depth: rest.depth || "MEDIUM",
  tags: rest.tags || [],
  ageSuitability: "FAMILY",
  eventCompatibility: rest.eventCompatibility || ["ALL"],
  portfolioTraits: traits,
  conflictRules: rest.conflictRules || [],
  weight: rest.weight || 1,
  finale: Boolean(rest.finale),
  mystery: Boolean(rest.mystery),
  mysteryHint: rest.mysteryHint || null,
  purchaseLimit: rest.purchaseLimit || 1,
  active: true,
});

const lots = [
  lot({ id: "peace-of-mind", title: "Peace of Mind", category: "Peace", icon: "😌", basePrice: 8, modes: DEEP, traits: ["Peace", "Security"], finale: true, tags: ["calm", "balance"] }),
  lot({ id: "true-love", title: "True Love", category: "Love", icon: "❤️", basePrice: 9, modes: DEEP, traits: ["Relationships"], auctionType: "SEALED_BID", finale: true, tags: ["connection"] }),
  lot({ id: "financial-freedom", title: "Financial Freedom", category: "Money", icon: "💰", basePrice: 11, modes: SUCCESS, traits: ["Security", "Freedom"], finale: true, tags: ["finance", "independence"] }),
  lot({ id: "excellent-health", title: "Excellent Health", category: "Health", icon: "❤️‍🩹", basePrice: 10, modes: DEEP, traits: ["Health", "Security"], tags: ["wellbeing"] }),
  lot({ id: "happy-family", title: "A Happy Family Life", category: "Family", icon: "🏡", basePrice: 9, modes: DEEP, traits: ["Relationships", "Security"], tags: ["home", "connection"] }),
  lot({ id: "loyal-friends", title: "Three Truly Loyal Friends", category: "Friendship", icon: "🫂", basePrice: 7, modes: [...DEEP, "friends-night"], traits: ["Relationships"], auctionType: "FIXED_PRICE", purchaseLimit: 12, tags: ["friendship"] }),
  lot({ id: "more-time", title: "More Time for What Matters", category: "Time", icon: "⏳", basePrice: 10, modes: DEEP, traits: ["Freedom", "Peace"], finale: true, auctionType: "SEALED_BID", tags: ["time"] }),
  lot({ id: "know-purpose", title: "Know Your Purpose", category: "Purpose", icon: "🌱", basePrice: 8, modes: DEEP, traits: ["Growth", "Peace"], auctionType: "SEALED_BID", finale: true, tags: ["meaning"] }),
  lot({ id: "extraordinary-intelligence", title: "Extraordinary Intelligence", category: "Knowledge", icon: "🧠", basePrice: 9, modes: ALL_CORE, traits: ["Growth", "Achievement"], tags: ["learning"] }),
  lot({ id: "knowledge-for-life", title: "A Lifetime of Curiosity", category: "Knowledge", icon: "📚", basePrice: 6, modes: [...ALL_CORE, "deep-life"], traits: ["Growth"], tags: ["learning", "curiosity"] }),
  lot({ id: "dream-career", title: "Your Dream Career", category: "Career", icon: "🚀", basePrice: 10, modes: SUCCESS, traits: ["Achievement", "Growth"], tags: ["work"] }),
  lot({ id: "own-business", title: "A Business You Believe In", category: "Career", icon: "🏢", basePrice: 10, modes: SUCCESS, traits: ["Achievement", "Freedom"], tags: ["business"] }),
  lot({ id: "career-recognition", title: "Career Recognition", category: "Achievement", icon: "🏆", basePrice: 8, modes: SUCCESS, traits: ["Achievement"], tags: ["career"] }),
  lot({ id: "high-salary", title: "A Very High Salary", category: "Money", icon: "📈", basePrice: 9, modes: SUCCESS, traits: ["Security", "Achievement"], tags: ["income"] }),
  lot({ id: "freedom-from-debt", title: "Freedom From Debt", category: "Money", icon: "🔓", basePrice: 7, modes: SUCCESS, traits: ["Security", "Freedom"], auctionType: "FIXED_PRICE", purchaseLimit: 12, tags: ["finance"] }),
  lot({ id: "retire-early", title: "Retire Early", category: "Freedom", icon: "🏝️", basePrice: 11, modes: SUCCESS, traits: ["Freedom", "Security"], tags: ["time", "finance"] }),
  lot({ id: "investment-luck", title: "Remarkable Investment Luck", category: "Money", icon: "🍀", basePrice: 6, modes: ["money-success", "random-mix", "chaos"], traits: ["Security"], tone: "PLAYFUL", tags: ["luck"] }),
  lot({ id: "dream-company", title: "Build Your Dream Company", category: "Career", icon: "✨", basePrice: 12, modes: SUCCESS, traits: ["Achievement", "Freedom"], finale: true, tags: ["business", "legacy"] }),
  lot({ id: "dream-home", title: "Your Dream Home", category: "Home", icon: "🏠", basePrice: 10, modes: [...SUCCESS, "dream-life"], traits: ["Security", "Comfort"], tags: ["home"] }),
  lot({ id: "live-anywhere", title: "Live Anywhere in the World", category: "Freedom", icon: "🌍", basePrice: 9, modes: DREAM, traits: ["Freedom", "Experience"], tags: ["location"] }),
  lot({ id: "travel-world", title: "Travel the World", category: "Travel", icon: "✈️", basePrice: 8, modes: DREAM, traits: ["Experience", "Freedom"], tags: ["travel"] }),
  lot({ id: "creative-freedom", title: "Creative Freedom", category: "Creativity", icon: "🎨", basePrice: 7, modes: DREAM, traits: ["Freedom", "Growth"], tags: ["creative"] }),
  lot({ id: "perfect-balance", title: "A Sustainable Work-Life Balance", category: "Peace", icon: "⚖️", basePrice: 9, modes: [...DREAM, "money-success"], traits: ["Peace", "Freedom"], tags: ["work", "time"] }),
  lot({ id: "year-off", title: "A Year With No Schedule", category: "Time", icon: "🗓️", basePrice: 8, modes: DREAM, traits: ["Freedom", "Experience"], tags: ["time"] }),
  lot({ id: "adventure-year", title: "One Unforgettable Adventure Year", category: "Adventure", icon: "🧭", basePrice: 7, modes: DREAM, traits: ["Experience"], tone: "BOLD", tags: ["travel", "adventure"] }),
  lot({ id: "cozy-everyday-life", title: "A Cozy Everyday Life", category: "Comfort", icon: "☕", basePrice: 6, modes: DREAM, traits: ["Comfort", "Peace"], auctionType: "FIXED_PRICE", purchaseLimit: 12, tags: ["comfort"] }),
  lot({ id: "free-travel-friends", title: "Free Travel With Friends", category: "Travel", icon: "🚌", basePrice: 7, modes: FRIENDS, traits: ["Experience", "Relationships"], tags: ["friends", "travel"] }),
  lot({ id: "no-early-mornings", title: "Never Have to Wake Up Early", category: "Funny", icon: "😴", basePrice: 4, modes: FRIENDS, traits: ["Comfort", "Freedom"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "unlimited-food", title: "Unlimited Free Food", category: "Fun", icon: "🍜", basePrice: 5, modes: FRIENDS, traits: ["Comfort", "Experience"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "perfect-wifi", title: "Perfect Wi-Fi Forever", category: "Funny", icon: "📶", basePrice: 4, modes: FRIENDS, traits: ["Comfort"], auctionType: "FIXED_PRICE", purchaseLimit: 12, tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "win-arguments", title: "Always Win Friendly Arguments", category: "Funny", icon: "🎤", basePrice: 5, modes: FRIENDS, traits: ["Achievement"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "no-traffic", title: "Never Wait in Traffic", category: "Comfort", icon: "🚦", basePrice: 5, modes: FRIENDS, traits: ["Comfort", "Time"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "window-seat", title: "Always Get the Window Seat", category: "Funny", icon: "🪟", basePrice: 3, modes: FRIENDS, traits: ["Comfort", "Experience"], auctionType: "FIXED_PRICE", purchaseLimit: 12, tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "instant-replies", title: "Your Friends Always Reply Immediately", category: "Friendship", icon: "💬", basePrice: 5, modes: FRIENDS, traits: ["Relationships"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "never-lose-phone", title: "Never Lose Your Phone", category: "Funny", icon: "📱", basePrice: 4, modes: FRIENDS, traits: ["Security", "Comfort"], auctionType: "FIXED_PRICE", purchaseLimit: 12, tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "perfect-group-photo", title: "A Perfect Group Photo Every Time", category: "Social Life", icon: "📸", basePrice: 4, modes: FRIENDS, traits: ["Relationships", "Experience"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "always-pick-restaurant", title: "Always Know Where the Group Should Eat", category: "Funny", icon: "🍕", basePrice: 4, modes: FRIENDS, traits: ["Experience"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "inside-jokes", title: "Endless Great Inside Jokes", category: "Friendship", icon: "😂", basePrice: 5, modes: FRIENDS, traits: ["Relationships", "Experience"], auctionType: "SEALED_BID", tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "concert-tickets", title: "Front-Row Tickets With Your Friends", category: "Experiences", icon: "🎶", basePrice: 6, modes: FRIENDS, traits: ["Experience", "Relationships"], tone: "PLAYFUL", depth: "LIGHT" }),
  lot({ id: "undo-mistake", title: "Undo One Past Mistake", category: "Personal Growth", icon: "↩️", basePrice: 10, modes: ["deep-life", "random-mix", "chaos"], traits: ["Growth", "Peace"], auctionType: "SEALED_BID", depth: "DEEP", finale: true }),
  lot({ id: "second-chance", title: "One Guaranteed Second Chance", category: "Personal Growth", icon: "🌅", basePrice: 9, modes: DEEP, traits: ["Growth", "Hope"], auctionType: "SEALED_BID", depth: "DEEP", finale: true }),
  lot({ id: "healthy-years", title: "Twenty Extra Healthy Years", category: "Health", icon: "🌿", basePrice: 12, modes: DEEP, traits: ["Health", "Time"], auctionType: "SEALED_BID", depth: "DEEP", finale: true }),
  lot({ id: "decision-clarity", title: "Clarity About Your Next Big Decision", category: "Confidence", icon: "🎯", basePrice: 8, modes: DEEP, traits: ["Growth", "Peace"], mystery: true, mysteryHint: "Something that could make the next step feel clearer.", tags: ["clarity"] }),
  lot({ id: "daily-motivation", title: "Wake Up Motivated Every Day", category: "Discipline", icon: "💪", basePrice: 8, modes: [...DEEP, "money-success"], traits: ["Growth", "Achievement"], tags: ["motivation"] }),
  lot({ id: "courage-start-again", title: "The Courage to Start Again", category: "Personal Growth", icon: "🔥", basePrice: 9, modes: DEEP, traits: ["Growth", "Freedom"], auctionType: "SEALED_BID", finale: true }),
  lot({ id: "forgiveness", title: "The Space to Forgive", category: "Peace", icon: "🕊️", basePrice: 7, modes: ["deep-life", "random-mix"], traits: ["Peace", "Relationships"], depth: "DEEP" }),
  lot({ id: "proud-of-life", title: "Feel Proud of the Life You Built", category: "Legacy", icon: "🌟", basePrice: 11, modes: DEEP, traits: ["Achievement", "Peace"], auctionType: "SEALED_BID", finale: true, depth: "DEEP" }),
  lot({ id: "privacy", title: "Complete Personal Privacy", category: "Privacy", icon: "🔒", basePrice: 7, modes: ALL_CORE, traits: ["Security", "Freedom"], tags: ["privacy"] }),
  lot({ id: "confidence", title: "Quiet, Lasting Confidence", category: "Confidence", icon: "🎯", basePrice: 7, modes: ALL_CORE, traits: ["Growth", "Peace"], tags: ["confidence"] }),
  lot({ id: "discipline", title: "Reliable Self-Discipline", category: "Discipline", icon: "💪", basePrice: 6, modes: [...ALL_CORE, "money-success"], traits: ["Growth", "Achievement"], tags: ["discipline"] }),
  lot({ id: "public-fame", title: "Worldwide Fame", category: "Achievement", icon: "🌟", basePrice: 8, modes: ALL_CORE, traits: ["Achievement", "Social"], tags: ["fame"] }),
  lot({ id: "future-glimpse", title: "A Glimpse of One Possible Future", category: "Future", icon: "🔭", basePrice: 8, modes: ["random-mix", "chaos", "dream-life"], traits: ["Growth", "Experience"], mystery: true, mysteryHint: "A window into what might be—not a promise.", rarity: "RARE" }),
  lot({ id: "money-cant-buy", title: "More Time With People You Love", category: "Time", icon: "🫶", basePrice: 9, modes: ["deep-life", "random-mix", "chaos"], traits: ["Relationships", "Time"], mystery: true, mysteryHint: "Something money cannot easily buy.", auctionType: "SEALED_BID", rarity: "RARE", finale: true, depth: "DEEP" }),
  lot({ id: "no-regrets", title: "A Life With Fewer Regrets", category: "Peace", icon: "🌄", basePrice: 11, modes: DEEP, traits: ["Peace", "Growth"], finale: true, depth: "DEEP", rarity: "RARE" }),
];

module.exports = Object.freeze({ version: 1, locale: "en", lots: Object.freeze(lots) });
