"use strict";

export const PLAY_GAMES = [
  {
    id: "play-life",
    title: "Play Life",
    tagline: "Atmospheric Emotional Journey",
    description: "A gentle, reflective scene engine tailored to your current emotional state. Choose your mood, explore honest paths, and find thoughtful moments with zero scoring and complete privacy.",
    category: "solo",
    players: "1 Player",
    duration: "3–5 min",
    status: "available",
    icon: "🌱",
    route: "/play/life",
    legacyRoute: "/play-life",
    badge: "Reflective",
    theme: "emerald",
  },
  {
    id: "this-or-that",
    title: "This or That: Life Choices",
    tagline: "Fast Dilemmas & Trade-offs",
    description: "Ten swift, thought-provoking philosophical dilemmas and lifestyle trade-offs. Discover your hidden decision tendencies and view your personal choice archetype.",
    category: "solo",
    players: "1 Player",
    duration: "2–3 min",
    status: "available",
    icon: "⚖️",
    route: "/play/this-or-that",
    badge: "Quick Choice",
    theme: "indigo",
  },
  {
    id: "who-knows-me-better",
    title: "Who Knows Me Better?",
    tagline: "Live Social Guessing Party",
    description: "One host, multiple friends. The host locks in their personal truths, and friends race against the timer to guess the real answer. Server-scored and synchronized in real time.",
    category: "multiplayer",
    players: "2–12 Players",
    duration: "5–10 min",
    status: "available",
    icon: "👀",
    route: "/play/who-knows-me-better",
    legacyRoute: "/play-with-friends",
    badge: "Live Party",
    theme: "amber",
  },
  {
    id: "life-auction",
    title: "Life Auction",
    tagline: "100 Coins. What Matters Most?",
    description: "Each player starts with 100 Life Coins. You cannot buy everything. Bid against friends on fictional life milestones, dream experiences, and wild card events in open and sealed auctions.",
    category: "multiplayer",
    players: "2–12 Players",
    duration: "8–15 min",
    status: "available",
    icon: "🪙",
    route: "/play/life-auction",
    legacyRoute: "/play-with-friends",
    badge: "Live Auction",
    theme: "rose",
  },
  {
    id: "rapid-reflections",
    title: "Rapid Reflections",
    tagline: "Daily 60-Second Mindset Check",
    description: "A fast 60-second clarity check to align your priorities and mindset before a big day or quiet evening.",
    category: "solo",
    players: "1 Player",
    duration: "1 min",
    status: "coming_soon",
    icon: "⏱️",
    badge: "Coming Soon",
    theme: "slate",
  },
];

export const getGameById = (id) => PLAY_GAMES.find((g) => g.id === id) || null;
export const getAvailableGames = () => PLAY_GAMES.filter((g) => g.status === "available");
export const getSoloGames = () => PLAY_GAMES.filter((g) => g.category === "solo");
export const getMultiplayerGames = () => PLAY_GAMES.filter((g) => g.category === "multiplayer");
